# Generated by Django 4.2.5 on 2023-09-24 07:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='emi_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='transactions',
            name='transaction_type',
            field=models.CharField(choices=[('CREDIT', 'CREDIT'), ('DEBIT', 'DEBIT')], default='CREDIT', max_length=10),
        ),
    ]
