# Generated by Django 4.2.5 on 2023-09-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transactions_emi_date_transactions_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplications',
            name='emi_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='loanapplications',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
