# Generated by Django 4.2.5 on 2023-09-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_loanapplications_emi_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplications',
            name='outstanding_principal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
