# Generated by Django 4.2.5 on 2023-09-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_loanapplications_outstanding_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactions',
            name='principal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
